# Generated by Django 4.2.1 on 2023-07-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audience_rating',
            field=models.CharField(max_length=10, null=True, verbose_name='audience_rating'),
        ),
    ]
