# Generated by Django 4.2.1 on 2023-07-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, default=None, to='movie.movie'),
        ),
    ]
