# Generated by Django 4.2.1 on 2023-07-24 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_profile_favorite_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_list',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='watch_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='watchlist', to='movie.movie'),
        ),
    ]
