# Generated by Django 4.2.1 on 2023-08-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_userwatchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='watch_list',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_movies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='watch_list',
        ),
    ]
