# Generated by Django 4.2.1 on 2023-08-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_movie_favorites_remove_movie_watch_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rank',
            field=models.PositiveSmallIntegerField(default='0', null=True, verbose_name='rank'),
        ),
    ]
