# Generated by Django 4.2.1 on 2023-08-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_movie_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='movie.profile'),
        ),
    ]
